spring:
  application:
    name: api-gateway
  profiles:
    active: development
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: load-simulator
        uri: lb://load-simulator
        predicates:
        - name: Path
          args:
            pattern: "/load-simulator/**"
        filters:
          - name: RewritePath
            args:
              regexp: "/load-simulator/(?<remaining>.*)"
              replacement: "/${remaining}"
      - id: order-delivery-service
        uri: lb://order-delivery-service
        predicates:
        - name: Path
          args:
            pattern: "/order-delivery-service/**"
        filters:
          - name: RewritePath
            args:
              regexp: "/order-delivery-service/(?<remaining>.*)"
              replacement: "/${remaining}"
server:
  port: 9090
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    com.memorynotfound: DEBUG
    org.apache.kafka.*: ERROR
---
spring:
  config:
    activate:
      on-profile: development
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
spring:
  config:
    activate:
      on-profile: docker
---
spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
      ribbon:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
  config:
    activate:
      on-profile: kubernetes
kubernetes.trust.certificates: true
# disable eureka
ribbon.eureka.enabled: false
eureka.client.enabled: false
prometheus.push.enabled: false
---
spring:
  config:
    activate:
      on-profile: test
eureka:
  client:
    enabled: false
