spring:
  application:
    name: load-simulator
  profiles:
    active: development
server:
  port: 0
order-service:
  host: "order-delivery-service"
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
---
spring:
  config:
    activate:
      on-profile:
        - docker
order-service:
  host: "order-delivery-service"
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  config:
    activate:
      on-profile:
        - test
order-service:
  host: "localhost"
eureka:
  client:
    enabled: false