spring:
  profiles:
    active: development
server:
  port: 0
order-service:
  host: "localhost"
---
spring:
  config:
    activate:
      on-profile:
        - docker
order-service:
  host: "order-delivery-service"
---
spring:
  config:
    activate:
      on-profile:
        - test
order-service:
  host: "localhost"