spring:
  profiles:
    active: development
  application:
    name: order-delivery-service
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
---
spring:
  config:
    activate:
      on-profile:
        - development
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile:
        - docker
  datasource:
    hikari:
      maximum-pool-size: 250
      connection-timeout: 1000
    platform: mysql
    url: jdbc:mysql://mysql:3306/orderweb
    username: mysqluser
    password: mysqlpw
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  config:
    activate:
      on-profile:
        - test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
eureka:
  client:
    enabled: false